services:
  boilerplate_elysia:
    restart: unless-stopped
    container_name: boilerplate_elysia
    image: ghcr.io/congacon619/boilerplate-elysia:latest
    env_file:
      - .env.prod
    expose:
      - "3000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - boilerplate_network

  nginx:
    restart: unless-stopped
    container_name: boilerplate_nginx
    image: nginx:alpine
    volumes:
      - ./dockers/configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3001:80"
    depends_on:
      - boilerplate_elysia
    networks:
      - boilerplate_network

networks:
  boilerplate_network:
    external: true
    name: boilerplate_network
